name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and authenticate to npm
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: "@your-scope"           # uprav na svůj scope nebo odstraň pro nescope balíčky
          always-auth: true
          auth-token: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Sync package.json version with Git tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "Updating package.json version to $TAG_VERSION"
          npm version $TAG_VERSION --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public
