name: Publish to Packagist

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{\"repository\":{\"url\":\"https://github.com/Filipeus-san/psqt\"}}" \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"