name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to npm
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc && cat ~/.npmrc

      - name: Sync package.json version with Git tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "Updating package.json version to $TAG_VERSION"
          npm version $TAG_VERSION --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public
